spring:
  config:
    activate:
      on-profile: "qa"


build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Tamilarasi - Developer"
    email: "tamilarasi.srinivasan@outlook.com"
  onCallSupport:
    - (91) 89407-73705
    - (555) 523-1345

