server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active:
      - "prod"
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "cards"
    description: "Cards Service"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

management:
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      spring:
        cards: DEBUG