##Start with base image
#FROM openjdk:17-jdk-slim
#
##Information about who maintains the image
#MAINTAINER tamilarasi
#
##Add the application jar to image
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#
##execute application
#ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]