server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active:
      - "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "loans"
    description: "Loans Service"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

management:
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"